config/routes.rb
FairyApp::Application.routes.draw do

  root to: 'housekeepers#new'

  resources :housekeepers, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :appointments

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	before_validation on: [:create] do
		self.scheduled_at = DateTime.now
	end
		
	validates :address, presence: true
	validates :scheduled_at, presence: true
	validates :start_at, presence: true
	validates :end_at, presence: true

	belongs_to :housekeeper

	def self.filter(curr)
	    sorted = Appointment.all.sort{|a,b| a.start_at <=> b.start_at}
	    sorted.select do |unbooked|
	    	curr.appointments.all? do |booking|
	    		!unbooked.start_at.between?(booking.start_at, booking.end_at) &&
	    		!unbooked.end_at.between?(booking.start_at, booking.end_at)
	    	end
	    end
  	end

end

app/models/housekeeper.rb
class Housekeeper < ActiveRecord::Base
  attr_reader :password
  validates :phone, presence: true, uniqueness: true, length: {minimum: 10, maximum: 10} 
  validates_format_of :phone, :with => /\d{10}/
  validates :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}


  after_initialize :ensure_session_token

  has_many :appointments

  def self.find_by_credentials(phone, password)
    housekeeper = Housekeeper.find_by(phone: phone)
    return nil unless housekeeper
    housekeeper.is_password?(password) ? housekeeper : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    generate_session_token
    self.save
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def generate_session_token
    # TA: This method should not set self.session_token, only return a random
    # string
    self.session_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_housekeeper
  helper_method :logged_in?

  def current_housekeeper
    @current_housekeeper ||= Housekeeper.find_by(session_token: session[:session_token])
  end

  def login!(housekeeper)
    @current_housekeeper = housekeeper
    session[:session_token] = current_housekeeper.reset_session_token!
  end

  def logged_in?
    !current_housekeeper.nil?
  end

  def logout!
    current_housekeeper.reset_session_token!
    session[:session_token] = nil
  end

  
  def require_housekeeper
    redirect_to new_session_url unless current_housekeeper
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def index
    @appointments = current_housekeeper.appointments
  end

  def new
    @appointments = Appointment.filter(current_housekeeper)
  end

  def create
    @appointment = current_housekeeper.appointments.new(appointment_params)
    if @appointment.save
      redirect_to appointment_url(@appointment)
    else
      flash.now[:errors] = @appointment.errors.full_messages
      render :new
    end
  end

  def update
    @appointment = Appointment.find(params[:id])
    if @appointment.update(appointment_params)
      redirect_to appointments_url
    else
      flash.now[:errors] = @appointment.errors.full_messages
      render :new
    end
  end

  private
  def appointment_params
    params.require(:appointment).permit(:address, :scheduled_at, :start_at, :end_at, :housekeeper_id)
  end

end

app/controllers/housekeepers_controller.rb
class HousekeepersController < ApplicationController

  def new
    if current_housekeeper
      redirect_to appointments_url
    end
    @housekeeper = Housekeeper.new
  end

  def create
    @housekeeper = Housekeeper.new(housekeeper_params)
    if @housekeeper.save
      login!(@housekeeper)
      redirect_to appointments_url
    else
      flash.now[:errors] = @housekeeper.errors.full_messages
      render :new
    end
  end

  private
  def housekeeper_params
    params.require(:housekeeper).permit(:phone, :password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @housekeeper = Housekeeper.new
  end

  def create
    @housekeeper = Housekeeper.find_by_credentials(
      params[:housekeeper][:phone],
      params[:housekeeper][:password])
    if @housekeeper
      login!(@housekeeper)
      redirect_to appointments_url
    else
      flash.now[:errors] = ["Incorrect Phone Number/Password"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/edit.html.erb
<!-- TA: If you have time, be sure to pull out the common logic in the forms into a partial -->
<h1>Edit Appointment</h1>

<form action="<%= appointment_url(@appointment) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= render 'shared/auth' %>

  <label for="title">Title</label>
  <input type="text" name="appointment[title]" id="title" value="<%= @appointment.title %>">

  <label for="body">Body</label>
  <input type="text" name="appointment[body]" id="body" value="<%= @appointment.body %>">

  <input type="submit" value="Update Appointment">

</form>

app/views/appointments/index.html.erb
<%= link_to "Book New Appointments", new_appointment_url %>

<h2>My Appointments</h2>

<% if @appointments.length != 0 %>
	<div class="info-panel">
		<p>Address</p>
		<p>Start Time</p>
		<p>End Time</p>

	</div>
<% else %>
	<h4>You don't have any booked appointments</h4>
<% end %>

<% @appointments.each do |appointment| %>
	<div class="appointment">
		<%= render partial: 'shared/booking_info', :locals => {:appointment => appointment} %>


		<form action="<%= appointment_url(appointment) %>" method="post">
		  <input type="hidden" name="_method" value="patch">
		  <%= render 'shared/auth' %>

		  <%= render partial: 'shared/hidden_fields', :locals => {:appointment => appointment} %>
	  	  <input type="hidden" name="appointment[housekeeper_id]" id="housekeeper_id" value="<%= nil %>">

		  <input type="submit" value="Remove Appointment">
		</form>

	</div>
<% end %>

<br>

app/views/appointments/new.html.erb
<%= link_to "Return to your Appointments", appointments_url %>

<h2>Book a New Appointment</h2>

<div class="info-panel">
	<p>Address</p>
	<p>Start Time</p>
	<p>End Time</p>

</div>

<% @appointments.each do |appointment| %>
  <% if !appointment.housekeeper_id %>
		<form action="<%= appointment_url(appointment) %>" method="post">
		  <input type="hidden" name="_method" value="patch">
		  <%= render 'shared/auth' %>

		  <%= render partial: 'shared/booking_info', :locals => {:appointment => appointment} %>


  		  <%= render partial: 'shared/hidden_fields', :locals => {:appointment => appointment} %>

	  	  <input type="hidden" name="appointment[housekeeper_id]" id="housekeeper_id" value="<%= current_housekeeper.id %>">

		  <input type="submit" value="Select Appointment">

		</form>
  <% end %>

<% end %>

app/views/housekeepers/new.html.erb
<h1>Create a Housekeeper Account</h1>

<form action="<%= housekeepers_url %>" method="post">
  <%= render 'shared/auth' %>

  <label for="phone">Phone Number</label>
  <input type="text" name="housekeeper[phone]" id="phone">

  <label for="password">Password</label>
  <input type="text" name="housekeeper[password]" id="password">

  <input type="submit" value="Sign Up">

</form>

<h4>Already have an account? <%= link_to "Login", new_session_url %> now</h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fairy Challenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
</head>
<body>

<% if current_housekeeper %>
  <%= current_housekeeper.phone %>
  <%= button_to "Sign Out", session_url, method: :delete %>
  <br/><br/>
<% end %>

<%= flash[:errors] %>

<%= yield %>

</body>
</html>

app/views/shared/_auth.html.erb
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

app/views/shared/_booking_info.html.erb
<div class="address"><%= appointment.address.to_s%></div>
<div class="start"><%= appointment.start_at.strftime("%m/%d %I:%M%p")%></div>
<div class="end"><%= appointment.end_at.strftime("%m/%d %I:%M%p")%></div>